package hieds;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





import admin.userPage;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Vilma Gaming
 */
public class Aform extends javax.swing.JFrame {

    /**
     * Creates new form Aform
     */
    public Aform() {
        initComponents();
    }
    
    Color narv=new Color(0,51,51);
    Color head=new Color(0,153,153);
    Color bodyc=new Color(0,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        SAVE = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        p_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        a_fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a_em = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        a_cont = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        a_status = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        a_addrss = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(570, 0, 110, 50);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel2.setText("ADOPTION FORM");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 0, 330, 50);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(730, 10, 20, 23);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        SAVE.setBackground(new java.awt.Color(0, 153, 153));
        SAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SAVEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SAVEMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SAVE");

        javax.swing.GroupLayout SAVELayout = new javax.swing.GroupLayout(SAVE);
        SAVE.setLayout(SAVELayout);
        SAVELayout.setHorizontalGroup(
            SAVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SAVELayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SAVELayout.setVerticalGroup(
            SAVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 60, 30));

        p_id.setBackground(new java.awt.Color(0, 153, 153));
        p_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        p_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 190, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Pet ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 40));

        a_fn.setBackground(new java.awt.Color(0, 153, 153));
        a_fn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        a_fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a_fn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(a_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel3.setText("Adopter's Full Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, 40));

        a_em.setBackground(new java.awt.Color(0, 153, 153));
        a_em.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        a_em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a_em.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(a_em, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 190, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Adopter's Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 40));

        a_cont.setBackground(new java.awt.Color(0, 153, 153));
        a_cont.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        a_cont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a_cont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(a_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 190, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Contact No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 40));

        gender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gender.setText("Adopter's Gender:");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 150, 30));

        female.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 70, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Adopter's Status:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, 30));

        male.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 60, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Address:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 50));

        a_status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        a_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Inrelationship", "Married", " " }));
        jPanel1.add(a_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 150, 30));

        a_addrss.setColumns(20);
        a_addrss.setLineWrap(true);
        a_addrss.setRows(5);
        a_addrss.setBorder(null);
        jScrollPane2.setViewportView(a_addrss);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 150, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseClicked
        Aform af = new Aform();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SAVEMouseClicked

    private void SAVEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseEntered
       SAVE.setBackground(narv);
    }//GEN-LAST:event_SAVEMouseEntered

    private void SAVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseExited
        SAVE.setBackground(head);
    }//GEN-LAST:event_SAVEMouseExited

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int a=JOptionPane.showConfirmDialog(null,"Confirm Exit?");
        if(a==JOptionPane.YES_OPTION){
            System.exit(0);
            dashboard dash = new dashboard();
            dash.setVisible(true);
            userPage up = new userPage();
            dash.maindesktop.add(up).setVisible(true);
        }
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public  static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SAVE;
    public javax.swing.JTextArea a_addrss;
    public javax.swing.JTextField a_cont;
    public javax.swing.JTextField a_em;
    public javax.swing.JTextField a_fn;
    public javax.swing.JComboBox<String> a_status;
    private javax.swing.JLabel exit;
    public javax.swing.JRadioButton female;
    public javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton male;
    public javax.swing.JTextField p_id;
    // End of variables declaration//GEN-END:variables
}

