package hieds;


import admin.userPage;
import admin.AdminDashboard;
import user.UserDashboard;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import java.lang.String;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vilma Gaming
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }
    
    static String type="";
    static String status= "";

    public static boolean LOGIN(String usern, String password){
        dbConnector connector = new dbConnector();
        
        try{
            String query = "SELECT * FROM tbl_user WHERE u_user = '"+usern+"'";
            ResultSet resultSet = connector.getData(query);
            if(resultSet.next()){
  
            String hashedPass = resultSet.getString("u_password");
            String rehashedPass = passwordHasher.hashPassword(password);
            
          System.out.println(""+hashedPass); 
          System.out.println(""+rehashedPass);  
          if(hashedPass.equals(rehashedPass)){
          type=resultSet.getString("u_type");
          status=resultSet.getString("u_status");    
          Session sess=Session.getInstance();
            sess.setUid(resultSet.getInt("u_id"));
            sess.setName(resultSet.getString("u_name"));
            sess.setEmail(resultSet.getString("u_email"));
            sess.setType(resultSet.getString("u_type"));
            sess.setStatus(resultSet.getString("u_status"));
        return true; 
        
        }else{
           return false;
        }
        }else{
           return false;
        }
        }catch (SQLException | NoSuchAlgorithmException ex){
         return false;
        }
    }
        
    void buttonDefaultColor(JPanel panel){
        panel.setBackground(defbutton);
        panel.setBorder(empty);
    }
            
    Color hover=new Color(0,102,102);
    Color defbutton=new Color(0,102,102);
    
    Color narv = new Color(0,102,102);
       Color head = new Color(51,204,255);
       Color body = new Color(0,153,153);
    
    Border empty=BorderFactory.createEmptyBorder();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nn = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IMAGE = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usern = new javax.swing.JTextField();
        loginf = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME TO PET ADOPTION SYSTEM!");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, 435, 58));

        nn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nn.setText("—");
        nn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nnMouseClicked(evt);
            }
        });
        jPanel6.add(nn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        exit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel6.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 760, 80);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IMAGE.setBackground(new java.awt.Color(0, 102, 102));
        IMAGE.setForeground(new java.awt.Color(0, 102, 102));
        IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Pink and Black Simple Pet Shop Logo.png"))); // NOI18N
        jPanel2.add(IMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 80, 410, 340));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 310, 420);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log in to continue");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        usern.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usern.setForeground(new java.awt.Color(51, 51, 51));
        usern.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(usern, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 40));

        loginf.setForeground(new java.awt.Color(255, 255, 255));
        loginf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginf.setText("New User? Click Here to Register");
        loginf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginfMouseClicked(evt);
            }
        });
        jPanel3.add(loginf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 200, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USER:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(51, 51, 51));
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 30));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(310, 0, 450, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_exitMouseClicked

    private void nnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nnMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_nnMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
     
    }//GEN-LAST:event_jPanel6MouseClicked

    private void loginfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginfMouseClicked
     REGISTRATIONF rf = new REGISTRATIONF();
     rf.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_loginfMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (LOGIN(usern.getText(), password.getText())) {
   if (!status.equals("Active")) {
        JOptionPane.showMessageDialog(null, "The account is not yet Active. Please contact the administrator");
        
    } else {
        JOptionPane.showMessageDialog(null, "Login Successfully!");
        if (type.equals("Admin")) {
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            this.dispose();
        } else if (type.equals("User")) {
            UserDashboard ud = new UserDashboard();
            ud.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No account type found, contact the Administrator.");
        }
    }
    }else{
         JOptionPane.showMessageDialog(null, "Invalid Account!");
     }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGE;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel loginf;
    private javax.swing.JLabel nn;
    private javax.swing.JTextField password;
    private javax.swing.JTextField usern;
    // End of variables declaration//GEN-END:variables
}
