/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author PC7
 */
public class CreateUserForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateUserForm
     */
    public CreateUserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        H1 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        usrn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        fn = new javax.swing.JLabel();
        emel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        utype = new javax.swing.JComboBox<>();
        passw = new javax.swing.JTextField();
        UPDATE = new javax.swing.JPanel();
        H2 = new javax.swing.JLabel();
        DELETE = new javax.swing.JPanel();
        H3 = new javax.swing.JLabel();
        CANCEL = new javax.swing.JPanel();
        H4 = new javax.swing.JLabel();
        REFRESH = new javax.swing.JPanel();
        H5 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JPanel();
        H6 = new javax.swing.JLabel();
        FN1 = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(0, 102, 102));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        H1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H1.setText("ADD");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, 30));

        FN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 30));

        usrn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usrn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(usrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 200, 30));

        em.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 30));

        fn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fn.setForeground(new java.awt.Color(255, 255, 255));
        fn.setText("Full Name:");
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 30));

        emel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        emel.setForeground(new java.awt.Color(255, 255, 255));
        emel.setText("Email:");
        jPanel3.add(emel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 30));

        user.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User:");
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 30));

        pass.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password:");
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 120, 30));

        type.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Account Type:");
        jPanel3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 120, 30));

        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", " " }));
        jPanel3.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 200, 30));

        passw.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 200, 30));

        UPDATE.setBackground(new java.awt.Color(0, 102, 102));
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPDATEMouseExited(evt);
            }
        });

        H2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H2.setText("UPDATE");

        javax.swing.GroupLayout UPDATELayout = new javax.swing.GroupLayout(UPDATE);
        UPDATE.setLayout(UPDATELayout);
        UPDATELayout.setHorizontalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        UPDATELayout.setVerticalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, 30));

        DELETE.setBackground(new java.awt.Color(0, 102, 102));
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });

        H3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H3.setText("DELETE");

        javax.swing.GroupLayout DELETELayout = new javax.swing.GroupLayout(DELETE);
        DELETE.setLayout(DELETELayout);
        DELETELayout.setHorizontalGroup(
            DELETELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        DELETELayout.setVerticalGroup(
            DELETELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

        CANCEL.setBackground(new java.awt.Color(0, 102, 102));
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });

        H4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H4.setText("CANCEL");

        javax.swing.GroupLayout CANCELLayout = new javax.swing.GroupLayout(CANCEL);
        CANCEL.setLayout(CANCELLayout);
        CANCELLayout.setHorizontalGroup(
            CANCELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        CANCELLayout.setVerticalGroup(
            CANCELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 30));

        REFRESH.setBackground(new java.awt.Color(0, 102, 102));
        REFRESH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REFRESHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REFRESHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REFRESHMouseExited(evt);
            }
        });

        H5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H5.setText("REFRESH");

        javax.swing.GroupLayout REFRESHLayout = new javax.swing.GroupLayout(REFRESH);
        REFRESH.setLayout(REFRESHLayout);
        REFRESHLayout.setHorizontalGroup(
            REFRESHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        REFRESHLayout.setVerticalGroup(
            REFRESHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(REFRESH, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 30));

        CLEAR.setBackground(new java.awt.Color(0, 102, 102));
        CLEAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLEARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLEARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLEARMouseExited(evt);
            }
        });

        H6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        H6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H6.setText("CLEAR");

        javax.swing.GroupLayout CLEARLayout = new javax.swing.GroupLayout(CLEAR);
        CLEAR.setLayout(CLEARLayout);
        CLEARLayout.setHorizontalGroup(
            CLEARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        CLEARLayout.setVerticalGroup(
            CLEARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 30));

        FN1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(FN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 200, 30));

        id.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("User ID:");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseClicked

    private void UPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseEntered

    private void UPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseExited

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseClicked

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseExited

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseClicked

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseEntered

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseExited

    private void REFRESHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFRESHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_REFRESHMouseClicked

    private void REFRESHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFRESHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_REFRESHMouseEntered

    private void REFRESHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFRESHMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_REFRESHMouseExited

    private void CLEARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARMouseClicked

    private void CLEARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARMouseEntered

    private void CLEARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        AdminDashboard ab = new AdminDashboard();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CANCEL;
    private javax.swing.JPanel CLEAR;
    private javax.swing.JPanel DELETE;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField FN1;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JPanel REFRESH;
    private javax.swing.JPanel UPDATE;
    private javax.swing.JPanel add;
    private javax.swing.JTextField em;
    private javax.swing.JLabel emel;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField passw;
    private javax.swing.JLabel type;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usrn;
    private javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
